name: deploy the frontend

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: build and push
        uses: docker/build-push-action@v4
        with: 
          context: .
          file: ./docker/Dockerfile.frontend
          build-args:
            DATABASE_URL=${{secrets.DATABASE_URL}}
          push: true
          tags: kuntalmajee2557/todo-app-frontend:${{ github.sha }}

      - name: deploy to the vm
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ~/ssh_key
          chmod 700 /home/runner/ssh_key
          ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@15.206.172.121 -t "docker stop user_frontend && docker rm user_frontend && docker run --name user_frontend -d -p 3000:3000 kuntalmajee2557/todo-app-frontend:${{ github.sha }}"

 


